/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        /* Prototyping Kit — Neutral */
        'neutral-light-lightest':  '#FFFFFF',
        'neutral-light-light':     '#F8F9FE',
        'neutral-light-medium':    '#E8E9F1',
        'neutral-light-darkest':   '#C5C6CC',
        'neutral-dark-lightest':   '#8F9098',
        'neutral-dark-light':      '#71727A',
        'neutral-dark-medium':     '#494A50',
        'neutral-dark-dark':       '#2F3036',
        'neutral-dark-darkest':    '#1F2024',

        /* Prototyping Kit — Highlight (Brand Blue) */
        'highlight-lightest':      '#EAF2FF',
        'highlight-light':         '#B4DBFF',
        'highlight-darkest':       '#3370AB',

        /* Prototyping Kit — Support */
        'success-light':           '#E7F4E8',
        'success':                 '#3AC0A0',
        'warning-light':           '#FFF4E4',
        'warning':                 '#FFB37C',
        'error-light':             '#FFE2E5',
        'error':                   '#FF616D',
        'error-dark':              '#ED3241',

        /* Semantic aliases — used by existing components */
        'text-primary':            '#1F2024',
        'text-secondary':          '#71727A',
        'text-tertiary':           '#8F9098',
        'text-on-brand':           '#FFFFFF',
        'bg-default':              '#FFFFFF',
        'bg-hover':                '#F8F9FE',
        'bg-secondary':            '#F8F9FE',
        'bg-tertiary':             '#E8E9F1',
        'bg-neutral':              '#494A50',
        'bg-neutral-secondary':    '#8F9098',
        'bg-neutral-tertiary':     '#E8E9F1',
        'bg-brand':                '#2F3036',
        'bg-brand-tertiary':       '#EAF2FF',
        'border-default':          '#C5C6CC',
        'border-neutral':          '#2F3036',
        'border-neutral-secondary':'#71727A',
        'border-brand':            '#2F3036',
        'placeholder':             '#E8E9F1',
        'atlantis-blue-100':       '#EAF2FF',
        'atlantis-blue-400':       '#B4DBFF',
        'atlantis-blue-600':       '#3370AB',
        'brand-dark':              '#2F3036',
      },
      fontFamily: {
        heading: ['"Atlantis Resorts"', 'Georgia', 'serif'],
        sans:    ['"Averta PE"', 'system-ui', 'sans-serif'],
        ui:      ['"Inter"', 'system-ui', 'sans-serif'],
        mono:    ['"Roboto Mono"', 'monospace'],
      },
      fontSize: {
        'xs':   ['10px', { lineHeight: '1.4' }],
        'sm':   ['12px', { lineHeight: '1.4' }],
        'base': ['14px', { lineHeight: '1.4' }],
        'lg':   ['16px', { lineHeight: '1.4' }],
        'xl':   ['20px', { lineHeight: '1.2' }],
        '2xl':  ['24px', { lineHeight: '1.2' }],
        '3xl':  ['32px', { lineHeight: '1.2' }],
      },
      fontWeight: {
        regular:  '400',
        semibold: '600',
        bold:     '700',
      },
      spacing: {
        '0':    '0px',
        '1':    '4px',
        '1.5':  '6px',
        '2':    '8px',
        '3':    '12px',
        '4':    '16px',
        '5':    '20px',
        '6':    '24px',
        '8':    '32px',
        '10':   '40px',
        '12':   '48px',
        '14':   '56px',
        '16':   '64px',
        '17':   '68px',
        '19':   '76px',
        '22':   '88px',
        '24':   '96px',
      },
      borderRadius: {
        'sm':  '8px',
        'md':  '12px',
        'lg':  '16px',
      },
      boxShadow: {
        'card': '0px 4px 4px -1px rgba(12,12,13,0.05), 0px 4px 4px -1px rgba(12,12,13,0.10)',
      },
      maxWidth: {
        'mobile':  '390px',
        'content': '358px',
      },
      height: {
        'status-bar':    '59px',
        'page-heading':  '64px',
        'nav-bar':       '68px',
        'btn':           '40px',
        'btn-lg':        '48px',
        'btn-icon':      '36px',
        'tag':           '33px',
        'tag-toggle':    '32px',
        'checkbox':      '22px',
        'input':         '48px',
        'offer-card':    '119px',
      },
      width: {
        'mobile':        '390px',
        'content':       '358px',
        'btn-icon':      '36px',
        'card-portrait': '300px',
      },
    },
  },
  plugins: [],
}
